version: '3'
services:
  crawler:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    depends_on:
      - "db"
    environment:
      POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always